name: Build and Deploy to ECS
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        AWS_REGION: "us-east-1"
        ECR_URL: "520256696060.dkr.ecr.us-east-1.amazonaws.com"
        IMAGE_NAME: "pythonapp"

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: $AWS_REGION
        - name: Login to Aws ECR
          run: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URL

        - name: Build and Push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: $ECR_URL/$IMAGE_NAME:latest
            
